"""Career recommendation request/response schemas."""
from pydantic import BaseModel, Field, field_validator, model_validator
from typing import List, Optional, Union, Any


class CareerRequest(BaseModel):
    """Request schema for POST /ai/recommend-career."""

    student_id: Optional[str] = Field(
        default=None,
        description="Optional unique student identifier.",
        examples=["STU_1001"]
    )
    skills: List[str] = Field(
        default=[],
        description="Current learner skills (raw text — normalized internally).",
        examples=[["Python", "SQL", "Git"]],
    )
    current_skills: Optional[List[str]] = Field(
        default=None,
        description="Alias for 'skills'.",
        examples=[["Python", "SQL", "Git"]],
    )
    interests: Union[str, List[str]] = Field(
        default="",
        description="Free-text interests or list of interest keywords.",
        examples=["Artificial Intelligence, Machine Learning"],
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of career recommendations to return (1–20).",
        examples=[5]
    )

    @model_validator(mode="before")
    @classmethod
    def resolve_aliases(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "current_skills" in data and ("skills" not in data or not data["skills"]):
                data["skills"] = data["current_skills"]
            elif "skills" in data and ("current_skills" not in data or not data["current_skills"]):
                data["current_skills"] = data["skills"]
        return data

    @field_validator("top_k")
    @classmethod
    def top_k_positive(cls, v: int) -> int:
        if v < 1:
            raise ValueError("top_k must be at least 1")
        return v


class MissingSkillBrief(BaseModel):
    skill_id: str = Field(..., description="Canonical skill ID (e.g., SK_00264).", examples=["SK_00264"])
    skill_name: str = Field(..., description="Display name of the missing skill.", examples=["Machine Learning"])
    importance: str = Field(description="Priority importance: Critical | High | Medium | Low", examples=["Critical"])


class CareerRecommendationItem(BaseModel):
    career_id: str = Field(..., description="Canonical career ID (e.g., CA_042).", examples=["CA_042"])
    career_title: str = Field(..., description="Display title of the career.", examples=["AI Engineer"])
    career_domain: str = Field(default="", description="Industry domain category.", examples=["Artificial Intelligence"])
    match_score: float = Field(
        description="Overall profile-career fit score (0–100 scale).",
        examples=[87.4]
    )
    technical_match_score: float = Field(
        description="Technical skills direct coverage score (0–100 scale).",
        examples=[75.0]
    )
    matched_skills: List[str] = Field(
        default=[],
        description="Skills the learner already possesses for this career.",
        examples=[["Python", "SQL"]]
    )
    missing_skills: List[MissingSkillBrief] = Field(
        default=[],
        description="Required career skills the learner is currently missing.",
    )
    reason: str = Field(
        description="Human-readable explainable rationale generated by the AI engine.",
        examples=["Strong alignment with AI interests. Python and SQL match core engineering requirements."]
    )


class CareerResponse(BaseModel):
    """Response schema for POST /ai/recommend-career."""

    recommendations: List[CareerRecommendationItem] = Field(
        ..., description="List of ranked career recommendations ordered by match score descending."
    )
    total: int = Field(..., description="Total count of returned career recommendations.", examples=[5])
